import type {
  Agent,
  ActionIntent,
  ChatMessage,
  LedgerEntry,
  Run,
  ToolCall,
  User,
} from "./types";

/**
 * Fixed demo clock. Every timestamp in the seed set is anchored to this so the
 * prototype renders identically on the server and the client, and so countdowns
 * and "x minutes ago" labels stay believable in a live demo.
 */
export const DEMO_NOW = new Date("2026-08-28T14:12:00-04:00");

export const USERS: User[] = [
  {
    id: "u-mreyes",
    name: "Marisol Reyes",
    role: "requester",
    oktaGroup: "esq-ai-users",
    groups: [
      "esq-ai-users",
      "esq-ai-om",
      "esq-ai-scheduling",
      "esq-ai-clientsuccess",
      "esq-ai-approvers-om",
      "esq-ai-approvers-scheduling",
    ],
    initials: "MR",
  },
  {
    id: "u-dcarver",
    name: "Dana Carver",
    role: "approver",
    oktaGroup: "esq-ai-approvers-finance",
    groups: ["esq-ai-users", "esq-ai-finance", "esq-ai-approvers-finance"],
    initials: "DC",
  },
  {
    id: "u-dmarsh",
    name: "Devin Marsh",
    role: "platform",
    oktaGroup: "esq-ai-platform-owners",
    groups: ["esq-ai-users", "esq-ai-platform-owners"],
    initials: "DM",
  },
  {
    id: "u-jballowe",
    name: "Jim Ballowe",
    role: "platform",
    oktaGroup: "esq-ai-platform-owners",
    groups: ["esq-ai-users", "esq-ai-platform-owners"],
    initials: "JB",
  },
];

export const AGENTS: Agent[] = [
  {
    slug: "transcript-production-reconciler",
    name: "Transcript Production Reconciler",
    summary:
      "Finds transcripts marked produced that have no delivery on record, and corrects the ones where the evidence is unambiguous.",
    owner: "Marisol Reyes",
    team: "Order Management",
    version: "v2.4.1",
    trigger: "scheduled",
    triggerDetail: "Weekdays 06:00 ET",
    systems: ["NetSuite", "Box"],
    writeTier: "medium",
    tools: [
      "netsuite.query_records",
      "netsuite.load_record",
      "netsuite.modify_record",
      "netsuite.lookup_worksheet_details",
      "box.search_files_metadata",
    ],
    evalScore: 0.96,
    evalThreshold: 0.9,
    runsThisMonth: 214,
    medianRunSeconds: 41,
    entitledGroups: ["esq-ai-om", "esq-ai-finance"],
    status: "live",
  },
  {
    slug: "invoice-exception-handler",
    name: "Invoice Exception Handler",
    summary:
      "Reconciles disputed deposition invoices against the job record and drafts a credit memo when the billed services do not match what was delivered.",
    owner: "Dana Carver",
    team: "Revenue Operations",
    version: "v1.2.0",
    trigger: "event",
    triggerDetail: "NetSuite invoice dispute flag",
    systems: ["NetSuite", "Microsoft 365"],
    writeTier: "high",
    tools: [
      "netsuite.lookup_invoice_details",
      "netsuite.lookup_job_details",
      "netsuite.create_record",
      "m365.send_mail",
    ],
    evalScore: 0.91,
    evalThreshold: 0.9,
    runsThisMonth: 38,
    medianRunSeconds: 96,
    entitledGroups: ["esq-ai-finance"],
    status: "canary",
  },
  {
    slug: "deposition-scheduling-assistant",
    name: "Deposition Scheduling Assistant",
    summary:
      "Proposes reporter, videographer and interpreter assignments for unstaffed jobs using coverage rules, certifications and calendar availability.",
    owner: "Priya Raman",
    team: "Scheduling",
    version: "v3.0.2",
    trigger: "on-demand",
    triggerDetail: "Launched from the console or from NetSuite",
    systems: ["NetSuite", "Microsoft 365"],
    writeTier: "medium",
    tools: [
      "netsuite.query_records",
      "netsuite.lookup_job_details",
      "netsuite.modify_record",
      "m365.outlook_calendar_search",
    ],
    evalScore: 0.94,
    evalThreshold: 0.92,
    runsThisMonth: 611,
    medianRunSeconds: 58,
    entitledGroups: ["esq-ai-scheduling"],
    status: "live",
  },
  {
    slug: "client-onboarding-packet",
    name: "Client Onboarding Packet",
    summary:
      "Assembles the welcome packet, rate card and protective-order template for a newly closed firm, and files it to the client Box folder.",
    owner: "Alex Whitfield",
    team: "Client Success",
    version: "v1.5.3",
    trigger: "event",
    triggerDetail: "Salesforce opportunity moves to Closed Won",
    systems: ["Salesforce", "Box", "Microsoft 365"],
    writeTier: "medium",
    tools: [
      "salesforce.soqlQuery",
      "box.create_folder",
      "box.upload_file",
      "m365.send_mail",
    ],
    evalScore: 0.93,
    evalThreshold: 0.9,
    runsThisMonth: 27,
    medianRunSeconds: 132,
    entitledGroups: ["esq-ai-clientsuccess"],
    status: "live",
  },
  {
    slug: "it-intake-triage",
    name: "IT Intake Triage",
    summary:
      "Reads new IT Support tickets, classifies them, links duplicates, and drafts the first customer reply for a human to send.",
    owner: "Nate Oduya",
    team: "IT Support",
    version: "v4.1.0",
    trigger: "event",
    triggerDetail: "Jira issue created in project IT",
    systems: ["Atlassian", "NetSuite"],
    writeTier: "low",
    tools: [
      "jira.searchJiraIssuesUsingJql",
      "jira.getJiraIssue",
      "jira.editJiraIssue",
      "jira.addCommentToJiraIssue",
    ],
    evalScore: 0.89,
    evalThreshold: 0.88,
    runsThisMonth: 1_482,
    medianRunSeconds: 22,
    entitledGroups: ["esq-ai-itsupport"],
    status: "live",
  },
  {
    slug: "transcript-delivery-auditor",
    name: "Transcript Delivery Auditor",
    summary:
      "Checks that every produced transcript reached the ordering firm within the committed turnaround and flags the ones that did not.",
    owner: "Marisol Reyes",
    team: "Order Management",
    version: "v2.0.0",
    trigger: "scheduled",
    triggerDetail: "Daily 07:30 ET",
    systems: ["NetSuite", "Box"],
    writeTier: "read-only",
    tools: [
      "netsuite.query_records",
      "netsuite.lookup_worksheet_details",
      "box.search_files_metadata",
    ],
    evalScore: 0.98,
    evalThreshold: 0.9,
    runsThisMonth: 30,
    medianRunSeconds: 210,
    entitledGroups: ["esq-ai-finance"],
    status: "live",
  },
  {
    slug: "vendor-rate-variance",
    name: "Vendor Rate Variance Monitor",
    summary:
      "Compares service-partner invoices against the contracted rate card and reports variances above tolerance. Read-only by design.",
    owner: "Dana Carver",
    team: "Revenue Operations",
    version: "v1.0.4",
    trigger: "scheduled",
    triggerDetail: "Mondays 05:00 ET",
    systems: ["NetSuite"],
    writeTier: "read-only",
    tools: ["netsuite.query_records", "netsuite.lookup_pricing"],
    evalScore: 0.97,
    evalThreshold: 0.9,
    runsThisMonth: 4,
    medianRunSeconds: 480,
    entitledGroups: ["esq-ai-finance"],
    status: "live",
  },
  {
    slug: "expense-report-assembler",
    name: "Expense Report Assembler",
    summary:
      "Pulls receipts out of Outlook, normalizes the filenames, files them to Box and drafts the monthly expense report for review.",
    owner: "Jim Ballowe",
    team: "Information Technology",
    version: "v0.9.0",
    trigger: "scheduled",
    triggerDetail: "First business day, monthly",
    systems: ["Microsoft 365", "Box", "NetSuite"],
    writeTier: "low",
    tools: [
      "m365.outlook_email_search",
      "box.upload_file",
      "box.set_file_metadata",
      "netsuite.create_record",
    ],
    evalScore: 0.86,
    evalThreshold: 0.85,
    runsThisMonth: 1,
    medianRunSeconds: 340,
    entitledGroups: ["esq-ai-platform-owners"],
    status: "canary",
  },
];

const iso = (s: string) => s;

export const INTENTS: ActionIntent[] = [
  /* ---- Marisol Reyes: order management and scheduling ------------------- */
  {
    id: "AI-8845",
    runId: "run-4420",
    agentSlug: "transcript-production-reconciler",
    agentName: "Transcript Production Reconciler",
    createdAt: iso("2026-08-28T13:12:05-04:00"),
    expiresAt: iso("2026-08-28T17:12:05-04:00"),
    requestedBy: "Schedule: weekdays 06:00 ET",
    approverGroup: "esq-ai-approvers-om",
    system: "NetSuite",
    tool: "netsuite.modify_record",
    effect:
      "Move the transcript worksheet on job J15033910 back to Processing. It is marked Produced but was never submitted or delivered.",
    parameters: {
      recordType: "customrecord_worksheet",
      id: "884213",
      custrecord_ws_prod_status: "8 - Processing",
    },
    target: {
      label: "Transcript worksheet on J15033910 - Whitmore v. Cascade Utilities",
      recordId: "884213",
      url: "https://3756790.app.netsuite.com/app/accounting/project/project.nl?id=14642103",
    },
    diff: [
      { field: "Worksheet production status", before: "9 - Produced", after: "8 - Processing" },
    ],
    risk: "low",
    riskReason:
      "Single enumerated status field, reversible, no financial effect. It does put the transcript back in the production queue, which a person should know about.",
    payloadHash: "sha256:3d90ba14ff62e7…8b41",
    confidence: 0.95,
    confidenceBasis:
      "The transcriptionist submission timestamp is empty and no delivery artifact exists. Both point the same way, and neither is a judgement call.",
    reasoning:
      "The worksheet reads Produced, but the transcriptionist submission timestamp is empty and there is no delivery artifact in Box. A produced transcript always has both. This one was swept into Produced by a bulk update on 24 August that touched eleven worksheets, and the other ten have since been corrected by hand.",
    citations: [
      { label: "Submission timestamp", detail: "Empty. A real submission always stamps it." },
      { label: "Delivery artifact", detail: "No file in Box under this job, under any name." },
      { label: "Bulk update, 24 Aug", detail: "Touched 11 worksheets. 10 already corrected manually." },
    ],
    state: "pending",
  },
  {
    id: "AI-8846",
    runId: "run-4421",
    agentSlug: "deposition-scheduling-assistant",
    agentName: "Deposition Scheduling Assistant",
    createdAt: iso("2026-08-28T12:40:18-04:00"),
    expiresAt: iso("2026-08-28T20:40:18-04:00"),
    requestedBy: "Marisol Reyes",
    approverGroup: "esq-ai-approvers-scheduling",
    system: "NetSuite",
    tool: "netsuite.modify_record",
    effect:
      "Book certified Spanish interpreter Rosa Villalobos for job J15051104 in Miami on 4 September.",
    parameters: {
      recordType: "project",
      id: "15051104",
      custentity_assigned_interpreter: "Rosa Villalobos (VEND-8814)",
      custentity_interpreter_language: "Spanish",
      custentity_esquire_scheduling_status: "2 - Complete",
    },
    target: {
      label: "Job J15051104 - In re Sandoval",
      recordId: "15051104",
      url: "https://3756790.app.netsuite.com/app/accounting/project/project.nl?id=14642103",
    },
    diff: [
      { field: "Assigned interpreter", before: "(none)", after: "Rosa Villalobos" },
      { field: "Interpreter language", before: "(not set)", after: "Spanish" },
      { field: "Scheduling Status", before: "1 - In Progress", after: "2 - Complete" },
    ],
    risk: "medium",
    riskReason:
      "Booking a vendor creates an external commitment and a payable at the four-hour minimum.",
    confidence: 0.88,
    confidenceBasis:
      "Certification and availability are confirmed. The rate is the contracted Miami minimum, but no interpreter has been booked on this matter before.",
    payloadHash: "sha256:c17e40aa9b3d52…f6a8",
    monetaryImpact: "$680.00 estimated",
    reasoning:
      "Rosa Villalobos holds a current federal court interpreter certification for Spanish, is available all day on 4 September, and has covered eleven Miami depositions for us this year with no service issues. The two alternates are either uncertified for federal matters or already booked.",
    citations: [
      { label: "Certification", detail: "Federal Court Interpreter, Spanish, valid through 2028." },
      { label: "Availability", detail: "No conflicting bookings 4 Sep." },
      { label: "Rate card", detail: "Four-hour minimum at the contracted Miami rate." },
    ],
    state: "pending",
  },
  {
    id: "AI-8822",
    runId: "run-4396",
    agentSlug: "transcript-production-reconciler",
    agentName: "Transcript Production Reconciler",
    createdAt: iso("2026-08-26T06:03:11-04:00"),
    expiresAt: iso("2026-08-26T10:03:11-04:00"),
    requestedBy: "Schedule: weekdays 06:00 ET",
    approverGroup: "esq-ai-approvers-om",
    system: "NetSuite",
    tool: "netsuite.modify_record",
    effect:
      "Move the transcript worksheet on job J14889201 back to Processing. No delivery artifact could be found.",
    parameters: {
      recordType: "customrecord_worksheet",
      id: "879455",
      custrecord_ws_prod_status: "8 - Processing",
    },
    target: {
      label: "Transcript worksheet on J14889201 - Renfro v. Atlas Logistics",
      recordId: "879455",
      url: "https://3756790.app.netsuite.com/app/accounting/project/project.nl?id=14642103",
    },
    diff: [
      { field: "Worksheet production status", before: "9 - Produced", after: "8 - Processing" },
    ],
    risk: "low",
    riskReason: "Single enumerated status field, reversible, no financial effect.",
    payloadHash: "sha256:aa41c7028de915…2f77",
    confidence: 0.72,
    confidenceBasis:
      "No delivery artifact matched, but the submission timestamp is present, which contradicts the rest. One of the two sources is wrong and the records do not say which.",
    reasoning:
      "No file matching the delivery naming convention exists for this job. The submission timestamp is populated, which normally means the transcript was produced, so the two signals disagree.",
    citations: [
      { label: "Delivery artifact", detail: "No match on the expected naming convention." },
      { label: "Submission timestamp", detail: "Populated 21 Aug, which contradicts the above." },
    ],
    state: "rejected",
    decidedBy: "Marisol Reyes",
    decidedAt: iso("2026-08-26T08:41:52-04:00"),
    decisionNote:
      "The transcript was delivered. It was filed under the old naming convention, which is why the search missed it. Nothing to correct here, and the agent should be taught to check both conventions.",
  },

  /* ---- Dana Carver: revenue operations ---------------------------------- */
  {
    id: "AI-8844",
    runId: "run-4419",
    agentSlug: "invoice-exception-handler",
    agentName: "Invoice Exception Handler",
    createdAt: iso("2026-08-28T13:05:44-04:00"),
    expiresAt: iso("2026-08-28T19:05:44-04:00"),
    requestedBy: "Event: NetSuite invoice dispute flag",
    approverGroup: "esq-ai-approvers-finance",
    system: "NetSuite",
    tool: "netsuite.create_record",
    effect:
      "Issue a $6,120.00 credit memo against invoice INV-118231 for a deposition that was cancelled inside the notice window and never took place.",
    parameters: {
      recordType: "creditmemo",
      entity: "Pell Marchetti & Ruiz (CUST-39907)",
      createdFrom: "INV-118231",
      "line[0].item": "Capture - Traditional, Full Day",
      "line[0].amount": "-4,400.00",
      "line[1].item": "Videography - Full Day",
      "line[1].amount": "-1,720.00",
      memo: "Credit per job J15019844 cancelled 19 Aug, outside billable window",
      subsidiary: "Esquire Deposition Solutions LLC",
    },
    target: {
      label: "Invoice INV-118231 - Pell Marchetti & Ruiz",
      recordId: "118231",
      url: "https://3756790.app.netsuite.com/app/accounting/transactions/custinvc.nl?id=74018815&whence=",
    },
    diff: [
      { field: "Invoice balance", before: "$6,120.00", after: "$0.00" },
      { field: "Dispute status", before: "Open", after: "Resolved - credited" },
      { field: "Job billing status", before: "Billed", after: "Cancelled, credited" },
    ],
    risk: "high",
    riskReason:
      "Full-value credit above the auto-approve ceiling, and it reverses recognized revenue on a closed period.",
    confidence: 0.96,
    confidenceBasis:
      "Cancellation timestamp, notice terms and untaken service instances all point the same way, with nothing contradicting.",
    payloadHash: "sha256:6e2bb90c4417da…d503",
    monetaryImpact: "$6,120.00",
    reasoning:
      "Job J15019844 is marked Cancelled with a cancellation timestamp of 19 August, six days before the scheduled date. The client's cancellation notice period is five business days, so nothing was billable. No service instance on the job ever moved past Scheduled, and no worksheets exist, which confirms nobody was dispatched.",
    citations: [
      { label: "Job status", detail: "11 - Cancelled, stamped 19 Aug 2026." },
      { label: "Service instances", detail: "2 instances, both still at Scheduled. None taken." },
      { label: "Contract terms", detail: "Five business days notice. Cancelled with six." },
    ],
    state: "pending",
  },
  {
    id: "AI-8843",
    runId: "run-4418",
    agentSlug: "invoice-exception-handler",
    agentName: "Invoice Exception Handler",
    createdAt: iso("2026-08-28T11:22:30-04:00"),
    expiresAt: iso("2026-08-29T11:22:30-04:00"),
    requestedBy: "Event: NetSuite invoice dispute flag",
    approverGroup: "esq-ai-approvers-finance",
    system: "NetSuite",
    tool: "netsuite.modify_record",
    effect:
      "Re-issue invoice INV-118226 against the correct billing entity. The firm merged in July and the old entity is no longer valid.",
    parameters: {
      recordType: "invoice",
      id: "118226",
      entity: "Calloway Reed LLP (CUST-41882)",
      "previousEntity": "Calloway & Associates (CUST-30114)",
      memo: "Re-issued to successor entity following July 2026 merger",
    },
    target: {
      label: "Invoice INV-118226 - Calloway Reed LLP",
      recordId: "118226",
      url: "https://3756790.app.netsuite.com/app/accounting/transactions/custinvc.nl?id=73998402&whence=",
    },
    diff: [
      { field: "Bill to", before: "Calloway & Associates", after: "Calloway Reed LLP" },
      { field: "Customer record", before: "CUST-30114", after: "CUST-41882" },
      { field: "Invoice total", before: "$3,275.00", after: "$3,275.00" },
    ],
    risk: "medium",
    riskReason:
      "Changing the billing entity moves an open receivable between customer records, which affects aging and collections.",
    confidence: 0.79,
    confidenceBasis:
      "The merger is recorded in Salesforce, but the successor entity was inferred from the ordering contact rather than stated on the invoice.",
    payloadHash: "sha256:9017cc35ea8b46…41e0",
    monetaryImpact: "$3,275.00 reassigned",
    reasoning:
      "Salesforce records the merger of Calloway & Associates into Calloway Reed LLP effective 1 July 2026, and the ordering contact on this job now sits under the successor account. The amount does not change, only who it is owed by.",
    citations: [
      { label: "Salesforce account", detail: "Calloway & Associates marked merged, 1 Jul 2026." },
      { label: "Ordering contact", detail: "Now attached to Calloway Reed LLP." },
      { label: "Amount", detail: "Unchanged at $3,275.00. This is not a repricing." },
    ],
    state: "pending",
  },
  {
    id: "AI-8825",
    runId: "run-4399",
    agentSlug: "invoice-exception-handler",
    agentName: "Invoice Exception Handler",
    createdAt: iso("2026-08-27T10:14:02-04:00"),
    expiresAt: iso("2026-08-27T16:14:02-04:00"),
    requestedBy: "Event: NetSuite invoice dispute flag",
    approverGroup: "esq-ai-approvers-finance",
    system: "NetSuite",
    tool: "netsuite.create_record",
    effect:
      "Issue a $1,480.00 credit memo against invoice INV-118170 for expedited delivery that was billed but delivered on the standard timeline.",
    parameters: {
      recordType: "creditmemo",
      entity: "Brightwater Legal Group (CUST-38221)",
      createdFrom: "INV-118170",
      "line[0].item": "Expedited Transcript Surcharge",
      "line[0].amount": "-1,480.00",
      memo: "Credit per job J14971233, expedited turnaround not met",
    },
    target: {
      label: "Invoice INV-118170 - Brightwater Legal Group",
      recordId: "118170",
      url: "https://3756790.app.netsuite.com/app/accounting/transactions/custinvc.nl?id=73744019&whence=",
    },
    diff: [
      { field: "Invoice balance", before: "$9,240.00", after: "$7,760.00" },
      { field: "Applied credits", before: "$0.00", after: "$1,480.00" },
    ],
    risk: "high",
    riskReason: "Financial write above the $1,000 auto-approve ceiling.",
    confidence: 0.93,
    confidenceBasis:
      "Delivery timestamp and surcharge terms are both explicit. Straightforward miss against a written commitment.",
    payloadHash: "sha256:52ff8ac1704be3…9c22",
    monetaryImpact: "$1,480.00",
    reasoning:
      "The expedited surcharge commits to a three-day turnaround. The transcript was delivered on day seven. The surcharge is therefore not earned.",
    citations: [
      { label: "Delivery timestamp", detail: "Day 7 against a 3-day commitment." },
      { label: "Surcharge terms", detail: "Refundable in full when the window is missed." },
    ],
    state: "executed",
    decidedBy: "Dana Carver",
    decidedAt: iso("2026-08-27T11:02:18-04:00"),
    decisionNote: "Clear miss. Credited in full rather than pro-rated.",
    receiptId: "RCPT-5588",
  },
  {
    id: "AI-8841",
    runId: "run-4417",
    agentSlug: "invoice-exception-handler",
    agentName: "Invoice Exception Handler",
    createdAt: iso("2026-08-28T13:47:12-04:00"),
    expiresAt: iso("2026-08-28T15:47:12-04:00"),
    requestedBy: "Event: NetSuite invoice dispute flag",
    approverGroup: "esq-ai-approvers-finance",
    system: "NetSuite",
    tool: "netsuite.create_record",
    effect:
      "Issue a $2,340.00 credit memo against invoice INV-118204 for videography and interpreter lines that were billed but not delivered.",
    parameters: {
      recordType: "creditmemo",
      entity: "Harrington & Boyle LLP (CUST-40218)",
      createdFrom: "INV-118204",
      "line[0].item": "Videography - Full Day",
      "line[0].amount": "-1,650.00",
      "line[1].item": "Interpreter - Spanish, 4hr minimum",
      "line[1].amount": "-690.00",
      memo: "Credit per job J15002121 service reconciliation",
      subsidiary: "Esquire Deposition Solutions LLC",
    },
    target: {
      label: "Invoice INV-118204 - Harrington & Boyle LLP",
      recordId: "118204",
      url: "https://3756790.app.netsuite.com/app/accounting/transactions/custinvc.nl?id=73912288&whence=",
    },
    diff: [
      { field: "Invoice balance", before: "$7,910.00", after: "$5,570.00" },
      { field: "Dispute status", before: "Open", after: "Resolved - credited" },
      { field: "Applied credits", before: "$0.00", after: "$2,340.00" },
    ],
    risk: "high",
    riskReason:
      "Financial write above the $1,000 auto-approve ceiling, and it reduces recognized revenue.",
    confidence: 0.94,
    confidenceBasis:
      "Service instances, worksheets and the client email agree that the lines were never delivered.",
    payloadHash: "sha256:9f2c41a8e7b0d5…c31e",
    monetaryImpact: "$2,340.00",
    reasoning:
      "Job J15002121 records a single Capture - Digital service instance. No videography or interpreter instance exists on the job, and no worksheets of type VID or INT were ever created. Both lines appear on the invoice because the original order carried them before the client reduced scope on 12 Aug. The reduction was never pushed to billing.",
    citations: [
      {
        label: "Job J15002121 service instances",
        detail: "1 instance: Capture - Digital. No Videography, no Interpreting.",
      },
      {
        label: "Worksheets on job",
        detail: "1 worksheet, type CR. No VID or INT worksheet exists.",
      },
      {
        label: "Client email, 12 Aug 2026",
        detail:
          "Harrington & Boyle paralegal confirms scope reduction to record-only coverage.",
      },
    ],
    state: "pending",
  },
  {
    id: "AI-8839",
    runId: "run-4415",
    agentSlug: "deposition-scheduling-assistant",
    agentName: "Deposition Scheduling Assistant",
    createdAt: iso("2026-08-28T13:31:40-04:00"),
    expiresAt: iso("2026-08-28T14:31:40-04:00"),
    requestedBy: "Marisol Reyes",
    approverGroup: "esq-ai-approvers-scheduling",
    system: "NetSuite",
    tool: "netsuite.modify_record",
    effect:
      "Assign certified reporter Grace Lindholm to job J15048812 and move the job to Esquire Confirmed.",
    parameters: {
      recordType: "project",
      id: "15048812",
      custentity_assigned_reporter: "Grace Lindholm (EMP-2291)",
      custentity_jobproductionstatus: "4 - Esquire Confirmed",
      custentity_esquire_scheduling_status: "2 - Complete",
    },
    target: {
      label: "Job J15048812 - Ortega v. Meridian Freight",
      recordId: "15048812",
      url: "https://3756790.app.netsuite.com/app/accounting/project/project.nl?id=14642103",
    },
    diff: [
      { field: "Assigned reporter", before: "(unassigned)", after: "Grace Lindholm" },
      { field: "Job Status", before: "2 - Scheduled", after: "4 - Esquire Confirmed" },
      { field: "Scheduling Status", before: "1 - In Progress", after: "2 - Complete" },
    ],
    risk: "medium",
    riskReason:
      "Staffing commitment creates an external obligation to the ordering firm and a payable to the reporter.",
    confidence: 0.91,
    confidenceBasis:
      "Certification, calendar and distance all check out. Two alternates were ruled out on stated grounds.",
    payloadHash: "sha256:4b71ea09cc2f18…7d40",
    reasoning:
      "Grace Lindholm holds an active CSR in Arizona, is clear on 3 Sep from 09:00 to 17:00 MST, and is 14 miles from the deposition site. The two alternates are either uncertified in Arizona or already booked.",
    citations: [
      { label: "Certification", detail: "AZ CSR #50441, valid through 31 Mar 2027." },
      { label: "Outlook availability", detail: "No conflicting events 3 Sep, 09:00-17:00 MST." },
      { label: "Coverage rule", detail: "Within the 50-mile no-travel-fee radius." },
    ],
    state: "pending",
  },
  {
    id: "AI-8836",
    runId: "run-4412",
    agentSlug: "client-onboarding-packet",
    agentName: "Client Onboarding Packet",
    createdAt: iso("2026-08-28T12:58:03-04:00"),
    expiresAt: iso("2026-08-28T18:58:03-04:00"),
    requestedBy: "Event: Salesforce Closed Won",
    approverGroup: "esq-ai-approvers-clientsuccess",
    system: "Box",
    tool: "box.update_folder_properties",
    effect:
      "Grant external collaborator access on the Kessler Ward Trial Services client folder to three named paralegals at the firm.",
    parameters: {
      folderId: "318844021",
      folderPath: "/Clients/Kessler Ward Trial Services",
      "collaborators[0]": "r.nakamura@kesslerward.com (Viewer Uploader)",
      "collaborators[1]": "t.abiodun@kesslerward.com (Viewer)",
      "collaborators[2]": "s.delacruz@kesslerward.com (Viewer)",
      notifyUsers: "true",
    },
    target: {
      label: "Box folder - Kessler Ward Trial Services",
      recordId: "318844021",
      url: "https://esquire.box.com/folder/318844021",
    },
    diff: [
      { field: "External collaborators", before: "0", after: "3" },
      { field: "Shared link", before: "None", after: "None (unchanged)" },
      { field: "Folder classification", before: "Client - Confidential", after: "Client - Confidential" },
    ],
    risk: "high",
    riskReason:
      "Grants people outside the Esquire tenant standing access to a folder classified Client - Confidential.",
    confidence: 0.82,
    confidenceBasis:
      "All three addresses appear on the executed agreement, but the agreement does not state what access level each should have.",
    payloadHash: "sha256:21d0f6bb4a9e73…be82",
    reasoning:
      "The three addresses appear on the executed services agreement as authorized contacts. Domain kesslerward.com matches the account record in Salesforce. No access is being granted beyond the single client folder.",
    citations: [
      { label: "Salesforce account", detail: "Kessler Ward Trial Services, domain kesslerward.com." },
      { label: "Services agreement", detail: "Section 4 lists the three contacts as authorized recipients." },
      { label: "Least privilege", detail: "Two of three are Viewer only; one needs upload for protective orders." },
    ],
    state: "pending",
  },
  {
    id: "AI-8830",
    runId: "run-4406",
    agentSlug: "transcript-production-reconciler",
    agentName: "Transcript Production Reconciler",
    createdAt: iso("2026-08-28T06:02:44-04:00"),
    expiresAt: iso("2026-08-28T10:02:44-04:00"),
    requestedBy: "Schedule: weekdays 06:00 ET",
    approverGroup: "esq-ai-approvers-om",
    system: "NetSuite",
    tool: "netsuite.modify_record",
    effect:
      "Move the transcript worksheet on job J14964046 back to Processing. It is marked Produced with nothing delivered behind it.",
    parameters: {
      recordType: "customrecord_worksheet",
      id: "881904",
      custrecord_ws_prod_status: "8 - Processing",
    },
    target: {
      label: "Transcript worksheet on J14964046 - Delgado v. Ridgeline Health",
      recordId: "881904",
      url: "https://3756790.app.netsuite.com/app/accounting/project/project.nl?id=14642103",
    },
    diff: [
      { field: "Worksheet production status", before: "9 - Produced", after: "8 - Processing" },
    ],
    risk: "low",
    riskReason: "Single enumerated status field, reversible, no financial effect.",
    payloadHash: "sha256:7ac3915de0f284…1a55",
    confidence: 0.96,
    confidenceBasis:
      "Same signature as the 24 August bulk update: empty submission timestamp, no artifact, no vendor activity since.",
    reasoning:
      "Marked Produced on 24 August with no submission timestamp and no delivery artifact. The transcription vendor has recorded no activity on this job since 19 August, so nothing was produced to deliver.",
    citations: [
      { label: "Submission timestamp", detail: "Empty." },
      { label: "Vendor activity", detail: "Nothing recorded since 19 Aug." },
    ],
    state: "approved",
    decidedBy: "Marisol Reyes",
    decidedAt: iso("2026-08-28T08:14:09-04:00"),
    decisionNote: "Same bulk-update batch as the others. Put it back in the queue.",
    receiptId: "RCPT-5590",
  },
  {
    id: "AI-8827",
    runId: "run-4402",
    agentSlug: "it-intake-triage",
    agentName: "IT Intake Triage",
    createdAt: iso("2026-08-27T16:41:20-04:00"),
    expiresAt: iso("2026-08-27T20:41:20-04:00"),
    requestedBy: "Event: Jira issue created",
    approverGroup: "esq-ai-approvers-itsupport",
    system: "Atlassian",
    tool: "jira.addCommentToJiraIssue",
    effect:
      "Post a public customer reply on IT-121602 telling the reporter the GFV button is absent because the transcript is still with the vendor.",
    parameters: {
      issueKey: "IT-121602",
      jsdPublic: "true",
      body: "Thanks for flagging this. The Grab for Validation button is not showing because…",
    },
    target: {
      label: "IT-121602 - GFV button missing on J14984429",
      recordId: "IT-121602",
      url: "https://esquire.atlassian.net/browse/IT-121602",
    },
    diff: [],
    risk: "medium",
    riskReason: "Customer-visible communication leaves the tenant once posted.",
    confidence: 0.86,
    confidenceBasis:
      "The vendor and due date explain the missing button. The wording of the reply is a judgement call, not a fact.",
    payloadHash: "sha256:e5580b1c7fa946…09cd",
    reasoning:
      "The transcription service instance on J14984429 still shows vendor SP To Be Assigned with a due date of 2 Sep. No transcript exists to validate, so the button is correctly hidden.",
    citations: [
      { label: "Service instance", detail: "Transcription - Basic, vendor SP To Be Assigned." },
      { label: "Known pattern", detail: "Matches four tickets resolved the same way on 28 Jun." },
    ],
    state: "rejected",
    decidedBy: "Nate Oduya",
    decidedAt: iso("2026-08-27T17:02:55-04:00"),
    decisionNote:
      "Reply is accurate but too terse for this reporter. I will send a rewritten version myself.",
  },
];

const tc = (t: Partial<ToolCall> & { id: string; tool: string }): ToolCall => ({
  system: "NetSuite",
  intent: "",
  parameters: {},
  verdict: "allowed",
  rule: "read-allow:role-bundle",
  latencyMs: 120,
  ...t,
});

export const RUNS: Run[] = [
  {
    id: "run-4421",
    agentSlug: "deposition-scheduling-assistant",
    agentName: "Deposition Scheduling Assistant",
    title: "Book interpreter for J15051104 - In re Sandoval",
    startedBy: "Marisol Reyes",
    trigger: "on-demand",
    startedAt: iso("2026-08-28T12:38:40-04:00"),
    state: "awaiting-approval",
    correlationId: "cid-b3d10f77",
    costUsd: 0.14,
    tokens: 12_800,
    intentIds: ["AI-8846"],
    steps: [
      { id: "s1", label: "Intake", detail: "Launched from the console by Marisol Reyes.", state: "done", at: "2026-08-28T12:38:40-04:00", durationMs: 110 },
      { id: "s2", label: "Screen interpreters", detail: "6 Spanish interpreters screened on certification, availability and Miami coverage.", state: "done", at: "2026-08-28T12:40:02-04:00", durationMs: 78_000 },
      { id: "s3", label: "Policy check", detail: "Vendor booking classified medium risk.", state: "done", at: "2026-08-28T12:40:16-04:00", durationMs: 140 },
      { id: "s4", label: "Await approval", detail: "Callback token issued to esq-ai-approvers-scheduling.", state: "waiting", at: "2026-08-28T12:40:18-04:00" },
      { id: "s5", label: "Execute", detail: "Book the interpreter and complete scheduling.", state: "pending" },
      { id: "s6", label: "Verify and receipt", detail: "Read-back and receipt.", state: "pending" },
    ],
    toolCalls: [
      tc({ id: "t1", tool: "netsuite.lookup_job_details", intent: "Read job J15051104 requirements.", parameters: { jobId: "15051104" }, resultSummary: "Miami, 4 Sep, Spanish interpreter required.", latencyMs: 260 }),
      tc({ id: "t2", tool: "netsuite.query_records", intent: "List certified Spanish interpreters covering Miami.", parameters: { language: "Spanish", market: "Miami" }, resultSummary: "6 candidates, 3 federally certified.", latencyMs: 610 }),
      tc({ id: "t3", tool: "netsuite.modify_record", intent: "Book Rosa Villalobos and complete scheduling.", parameters: { id: "15051104" }, verdict: "approval-required", rule: "scheduling.write.book_vendor requires esq-ai-approvers-scheduling", latencyMs: 140, actionIntentId: "AI-8846" }),
    ],
  },
  {
    id: "run-4420",
    agentSlug: "transcript-production-reconciler",
    agentName: "Transcript Production Reconciler",
    title: "Transcript marked produced with nothing delivered - J15033910",
    startedBy: "Schedule: weekdays 06:00 ET",
    trigger: "scheduled",
    startedAt: iso("2026-08-28T13:10:00-04:00"),
    state: "awaiting-approval",
    correlationId: "cid-4fa22e81",
    costUsd: 0.09,
    tokens: 7_400,
    intentIds: ["AI-8845"],
    steps: [
      { id: "s1", label: "Intake", detail: "Midday re-check pass.", state: "done", at: "2026-08-28T13:10:00-04:00", durationMs: 60 },
      { id: "s2", label: "Scan", detail: "1 worksheet found marked Produced with no delivery artifact.", state: "done", at: "2026-08-28T13:12:00-04:00", durationMs: 118_000 },
      { id: "s3", label: "Policy check", detail: "Low-risk enumerated field write; OM approval still required.", state: "done", at: "2026-08-28T13:12:03-04:00", durationMs: 110 },
      { id: "s4", label: "Await approval", detail: "Callback token issued to esq-ai-approvers-om.", state: "waiting", at: "2026-08-28T13:12:05-04:00" },
      { id: "s5", label: "Execute", detail: "Move the worksheet back to Processing.", state: "pending" },
      { id: "s6", label: "Verify and receipt", detail: "Read-back and receipt.", state: "pending" },
    ],
    toolCalls: [
      tc({ id: "t1", tool: "netsuite.query_records", intent: "Re-check for produced worksheets with no delivery since 06:00.", parameters: { sql: "SELECT id, custrecord_ws_job_hidden FROM CUSTOMRECORD_WORKSHEET WHERE …" }, resultSummary: "1 worksheet on J15033910.", latencyMs: 1_900 }),
      tc({ id: "t2", tool: "netsuite.modify_record", intent: "Move the worksheet back to Processing.", parameters: { id: "884213" }, verdict: "approval-required", rule: "om.write.worksheet_status requires esq-ai-approvers-om", latencyMs: 110, actionIntentId: "AI-8845" }),
    ],
  },
  {
    id: "run-4419",
    agentSlug: "invoice-exception-handler",
    agentName: "Invoice Exception Handler",
    title: "Invoice dispute INV-118231 - Pell Marchetti & Ruiz",
    startedBy: "Event: NetSuite dispute flag",
    trigger: "event",
    startedAt: iso("2026-08-28T13:03:10-04:00"),
    state: "awaiting-approval",
    correlationId: "cid-8c4901ab",
    costUsd: 0.36,
    tokens: 31_200,
    intentIds: ["AI-8844"],
    steps: [
      { id: "s1", label: "Intake", detail: "EventBridge event accepted.", state: "done", at: "2026-08-28T13:03:10-04:00", durationMs: 290 },
      { id: "s2", label: "Gather evidence", detail: "Invoice, job, service instances and cancellation record read.", state: "done", at: "2026-08-28T13:05:30-04:00", durationMs: 132_000 },
      { id: "s3", label: "Policy check", detail: "Full-value credit above the ceiling. High risk.", state: "done", at: "2026-08-28T13:05:42-04:00", durationMs: 170 },
      { id: "s4", label: "Await approval", detail: "Callback token issued to esq-ai-approvers-finance.", state: "waiting", at: "2026-08-28T13:05:44-04:00" },
      { id: "s5", label: "Execute", detail: "Create the credit memo.", state: "pending" },
      { id: "s6", label: "Verify and receipt", detail: "Read-back and receipt.", state: "pending" },
    ],
    toolCalls: [
      tc({ id: "t1", tool: "netsuite.lookup_invoice_details", intent: "Read invoice INV-118231.", parameters: { invoiceId: "118231" }, resultSummary: "2 lines, balance $6,120.00.", latencyMs: 320 }),
      tc({ id: "t2", tool: "netsuite.lookup_job_details", intent: "Read job J15019844.", parameters: { jobId: "15019844" }, resultSummary: "Cancelled 19 Aug. No instance past Scheduled.", latencyMs: 280 }),
      tc({ id: "t3", tool: "netsuite.create_record", intent: "Create a $6,120.00 credit memo.", parameters: { recordType: "creditmemo", amount: "6120.00" }, verdict: "approval-required", rule: "finance.write.credit_memo > $1000 requires esq-ai-approvers-finance", latencyMs: 170, actionIntentId: "AI-8844" }),
    ],
  },
  {
    id: "run-4418",
    agentSlug: "invoice-exception-handler",
    agentName: "Invoice Exception Handler",
    title: "Billing entity mismatch on INV-118226",
    startedBy: "Event: NetSuite dispute flag",
    trigger: "event",
    startedAt: iso("2026-08-28T11:20:00-04:00"),
    state: "awaiting-approval",
    correlationId: "cid-2ad77f30",
    costUsd: 0.21,
    tokens: 18_600,
    intentIds: ["AI-8843"],
    steps: [
      { id: "s1", label: "Intake", detail: "EventBridge event accepted.", state: "done", at: "2026-08-28T11:20:00-04:00", durationMs: 260 },
      { id: "s2", label: "Gather evidence", detail: "Invoice, Salesforce account history and ordering contact read.", state: "done", at: "2026-08-28T11:22:12-04:00", durationMs: 124_000 },
      { id: "s3", label: "Policy check", detail: "Billing entity change requires finance approval at any amount.", state: "done", at: "2026-08-28T11:22:28-04:00", durationMs: 150 },
      { id: "s4", label: "Await approval", detail: "Callback token issued to esq-ai-approvers-finance.", state: "waiting", at: "2026-08-28T11:22:30-04:00" },
      { id: "s5", label: "Execute", detail: "Re-issue against the successor entity.", state: "pending" },
      { id: "s6", label: "Verify and receipt", detail: "Read-back and receipt.", state: "pending" },
    ],
    toolCalls: [
      tc({ id: "t1", tool: "netsuite.lookup_invoice_details", intent: "Read invoice INV-118226.", parameters: { invoiceId: "118226" }, resultSummary: "Balance $3,275.00, entity CUST-30114.", latencyMs: 300 }),
      tc({ id: "t2", tool: "salesforce.soqlQuery", system: "Salesforce", intent: "Check the account for a merger record.", parameters: { soql: "SELECT Id, Name, ParentId FROM Account WHERE …" }, resultSummary: "Merged into Calloway Reed LLP, 1 Jul 2026.", latencyMs: 540 }),
      tc({ id: "t3", tool: "netsuite.modify_record", intent: "Re-issue against the successor entity.", parameters: { id: "118226" }, verdict: "approval-required", rule: "finance.write.invoice_reissue requires esq-ai-approvers-finance", latencyMs: 150, actionIntentId: "AI-8843" }),
    ],
  },
  {
    id: "run-4399",
    agentSlug: "invoice-exception-handler",
    agentName: "Invoice Exception Handler",
    title: "Expedited surcharge dispute INV-118170",
    startedBy: "Event: NetSuite dispute flag",
    trigger: "event",
    startedAt: iso("2026-08-27T10:11:00-04:00"),
    state: "complete",
    correlationId: "cid-7b0e5512",
    costUsd: 0.28,
    tokens: 24_100,
    intentIds: ["AI-8825"],
    steps: [
      { id: "s1", label: "Intake", detail: "EventBridge event accepted.", state: "done", at: "2026-08-27T10:11:00-04:00", durationMs: 240 },
      { id: "s2", label: "Gather evidence", detail: "Invoice, job and delivery timestamps read.", state: "done", at: "2026-08-27T10:13:50-04:00", durationMs: 158_000 },
      { id: "s3", label: "Policy check", detail: "Above the ceiling. High risk.", state: "done", at: "2026-08-27T10:14:00-04:00", durationMs: 160 },
      { id: "s4", label: "Await approval", detail: "Approved by Dana Carver at 11:02 ET.", state: "done", at: "2026-08-27T11:02:18-04:00", durationMs: 2_898_000 },
      { id: "s5", label: "Execute", detail: "Credit memo created. Idempotency key accepted once.", state: "done", at: "2026-08-27T11:02:20-04:00", durationMs: 710, attempts: 1 },
      { id: "s6", label: "Verify and receipt", detail: "Read-back confirmed the credit. Receipt RCPT-5588 written.", state: "done", at: "2026-08-27T11:02:22-04:00", durationMs: 400 },
    ],
    toolCalls: [
      tc({ id: "t1", tool: "netsuite.lookup_invoice_details", intent: "Read invoice INV-118170.", parameters: { invoiceId: "118170" }, resultSummary: "Expedited surcharge line, $1,480.00.", latencyMs: 310 }),
      tc({ id: "t2", tool: "netsuite.create_record", intent: "Create a $1,480.00 credit memo.", parameters: { recordType: "creditmemo" }, verdict: "approval-required", rule: "finance.write.credit_memo > $1000 requires esq-ai-approvers-finance", latencyMs: 160, actionIntentId: "AI-8825", resultSummary: "Approved and executed. Read-back confirmed." }),
    ],
  },
  {
    id: "run-4396",
    agentSlug: "transcript-production-reconciler",
    agentName: "Transcript Production Reconciler",
    title: "Delivery record sweep - 26 Aug",
    startedBy: "Schedule: weekdays 06:00 ET",
    trigger: "scheduled",
    startedAt: iso("2026-08-26T06:00:00-04:00"),
    state: "failed",
    correlationId: "cid-15ce8830",
    costUsd: 0.44,
    tokens: 38_900,
    intentIds: ["AI-8822"],
    steps: [
      { id: "s1", label: "Intake", detail: "Scheduled trigger fired.", state: "done", at: "2026-08-26T06:00:00-04:00", durationMs: 60 },
      { id: "s2", label: "Scan", detail: "3,980 worksheets scanned, 1 flagged as produced with no delivery.", state: "done", at: "2026-08-26T06:03:08-04:00", durationMs: 188_000 },
      { id: "s3", label: "Policy check", detail: "Low-risk enumerated field write.", state: "done", at: "2026-08-26T06:03:10-04:00", durationMs: 120 },
      { id: "s4", label: "Await approval", detail: "Rejected by Marisol Reyes. The orchestrator cancelled the write path.", state: "done", at: "2026-08-26T08:41:52-04:00" },
      { id: "s5", label: "Execute", detail: "Skipped. The run terminated on rejection with no side effects.", state: "failed" },
    ],
    toolCalls: [
      tc({ id: "t1", tool: "netsuite.query_records", intent: "Find worksheets marked Produced with no delivery artifact.", parameters: { sql: "SELECT id FROM CUSTOMRECORD_WORKSHEET WHERE custrecord_ws_prod_status = 9 …" }, resultSummary: "1 worksheet on J14889201.", latencyMs: 2_100 }),
      tc({ id: "t2", tool: "netsuite.modify_record", intent: "Move the worksheet back to Processing.", parameters: { id: "879455" }, verdict: "approval-required", rule: "om.write.worksheet_status requires esq-ai-approvers-om", latencyMs: 120, actionIntentId: "AI-8822", resultSummary: "Rejected by the approver. Nothing was written." }),
    ],
  },
  {
    id: "run-4417",
    agentSlug: "invoice-exception-handler",
    agentName: "Invoice Exception Handler",
    title: "Invoice dispute INV-118204 - Harrington & Boyle LLP",
    startedBy: "Event: NetSuite dispute flag",
    trigger: "event",
    startedAt: iso("2026-08-28T13:46:02-04:00"),
    state: "awaiting-approval",
    correlationId: "cid-2f81b4c0",
    costUsd: 0.42,
    tokens: 38_400,
    intentIds: ["AI-8841"],
    steps: [
      { id: "s1", label: "Intake", detail: "EventBridge event accepted; workload identity asserted.", state: "done", at: "2026-08-28T13:46:02-04:00", durationMs: 310 },
      { id: "s2", label: "Plan", detail: "Agent runtime started on an ephemeral Fargate task.", state: "done", at: "2026-08-28T13:46:04-04:00", durationMs: 1_900 },
      { id: "s3", label: "Gather evidence", detail: "6 reads across NetSuite invoice, job and worksheet records.", state: "done", at: "2026-08-28T13:46:31-04:00", durationMs: 24_600, attempts: 1 },
      { id: "s4", label: "Policy check", detail: "Gateway classified the write as high risk: financial, above ceiling.", state: "done", at: "2026-08-28T13:47:09-04:00", durationMs: 180 },
      { id: "s5", label: "Await approval", detail: "Callback token issued to esq-ai-approvers-finance. Timeout 15:47 ET, then escalate.", state: "waiting", at: "2026-08-28T13:47:12-04:00" },
      { id: "s6", label: "Execute", detail: "Credit memo creation, idempotency key bound to the payload hash.", state: "pending" },
      { id: "s7", label: "Verify and receipt", detail: "Read-back of the created record, then receipt written to the ledger.", state: "pending" },
    ],
    toolCalls: [
      tc({ id: "t1", tool: "netsuite.lookup_invoice_details", intent: "Read invoice INV-118204 header and lines.", parameters: { invoiceId: "118204" }, resultSummary: "5 lines, balance $7,910.00, dispute flag set.", latencyMs: 340 }),
      tc({ id: "t2", tool: "netsuite.lookup_job_details", intent: "Read service instances on job J15002121.", parameters: { jobId: "15002121", operation: "service_instances" }, resultSummary: "1 instance: Capture - Digital.", latencyMs: 290 }),
      tc({ id: "t3", tool: "netsuite.query_records", intent: "List worksheets attached to the job.", parameters: { sql: "SELECT id, name, custrecord_ws_prod_status FROM CUSTOMRECORD_WORKSHEET WHERE …" }, resultSummary: "1 worksheet, type CR.", latencyMs: 410 }),
      tc({ id: "t4", tool: "netsuite.create_record", intent: "Create a $2,340.00 credit memo against INV-118204.", parameters: { recordType: "creditmemo", amount: "2340.00" }, verdict: "approval-required", rule: "finance.write.credit_memo > $1000 requires esq-ai-approvers-finance", latencyMs: 180, actionIntentId: "AI-8841" }),
    ],
  },
  {
    id: "run-4415",
    agentSlug: "deposition-scheduling-assistant",
    agentName: "Deposition Scheduling Assistant",
    title: "Staff J15048812 - Ortega v. Meridian Freight",
    startedBy: "Marisol Reyes",
    trigger: "on-demand",
    startedAt: iso("2026-08-28T13:30:11-04:00"),
    state: "awaiting-approval",
    correlationId: "cid-77a0e412",
    costUsd: 0.18,
    tokens: 16_100,
    intentIds: ["AI-8839"],
    steps: [
      { id: "s1", label: "Intake", detail: "Launched from the console by Marisol Reyes.", state: "done", at: "2026-08-28T13:30:11-04:00", durationMs: 120 },
      { id: "s2", label: "Plan", detail: "Coverage rules loaded from the agent package.", state: "done", at: "2026-08-28T13:30:13-04:00", durationMs: 1_400 },
      { id: "s3", label: "Evaluate candidates", detail: "9 reporters screened on certification, distance and availability.", state: "done", at: "2026-08-28T13:31:22-04:00", durationMs: 62_000 },
      { id: "s4", label: "Policy check", detail: "Staffing write classified medium risk.", state: "done", at: "2026-08-28T13:31:38-04:00", durationMs: 150 },
      { id: "s5", label: "Await approval", detail: "Callback token issued. Timeout 14:31 ET, then escalate to the scheduling lead.", state: "waiting", at: "2026-08-28T13:31:40-04:00" },
      { id: "s6", label: "Execute", detail: "Assign reporter and advance job status.", state: "pending" },
      { id: "s7", label: "Verify and receipt", detail: "Read-back and receipt.", state: "pending" },
    ],
    toolCalls: [
      tc({ id: "t1", tool: "netsuite.lookup_job_details", intent: "Read job J15048812 header.", parameters: { jobId: "15048812" }, resultSummary: "Deposition 3 Sep, Phoenix AZ, no reporter.", latencyMs: 250 }),
      tc({ id: "t2", tool: "netsuite.query_records", intent: "List AZ-certified reporters.", parameters: { sql: "SELECT … FROM employee WHERE certification_state = 'AZ'" }, resultSummary: "9 candidates.", latencyMs: 520 }),
      tc({ id: "t3", tool: "m365.outlook_calendar_search", intent: "Check candidate availability on 3 Sep.", parameters: { window: "2026-09-03T09:00/17:00", tz: "America/Phoenix" }, resultSummary: "3 clear, 6 conflicted.", latencyMs: 880 }),
      tc({ id: "t4", tool: "netsuite.modify_record", intent: "Assign Grace Lindholm and confirm the job.", parameters: { id: "15048812" }, verdict: "approval-required", rule: "scheduling.write.assign_reporter requires esq-ai-approvers-scheduling", latencyMs: 150, actionIntentId: "AI-8839" }),
    ],
  },
  {
    id: "run-4416",
    agentSlug: "it-intake-triage",
    agentName: "IT Intake Triage",
    title: "Triage IT-121611 - Outlook add-in crash on transcript upload",
    startedBy: "Event: Jira issue created",
    trigger: "event",
    startedAt: iso("2026-08-28T13:58:47-04:00"),
    state: "executing",
    correlationId: "cid-c40b9911",
    costUsd: 0.03,
    tokens: 5_200,
    intentIds: [],
    steps: [
      { id: "s1", label: "Intake", detail: "Jira webhook accepted.", state: "done", at: "2026-08-28T13:58:47-04:00", durationMs: 90 },
      { id: "s2", label: "Plan", detail: "Classifier selected: duplicate-detection path.", state: "done", at: "2026-08-28T13:58:49-04:00", durationMs: 800 },
      { id: "s3", label: "Search duplicates", detail: "JQL sweep over the last 90 days.", state: "done", at: "2026-08-28T13:59:02-04:00", durationMs: 11_400 },
      { id: "s4", label: "Policy check", detail: "Label and component edits are inside the auto-approve bundle.", state: "done", at: "2026-08-28T13:59:05-04:00", durationMs: 110 },
      { id: "s5", label: "Execute", detail: "Applying labels and linking IT-121544 as a duplicate.", state: "active", at: "2026-08-28T13:59:06-04:00", attempts: 1 },
      { id: "s6", label: "Verify and receipt", detail: "Read-back and receipt.", state: "pending" },
    ],
    toolCalls: [
      tc({ id: "t1", tool: "jira.getJiraIssue", system: "Atlassian", intent: "Read IT-121611.", parameters: { issueKey: "IT-121611" }, resultSummary: "Unassigned, no component.", latencyMs: 210 }),
      tc({ id: "t2", tool: "jira.searchJiraIssuesUsingJql", system: "Atlassian", intent: "Find similar tickets.", parameters: { jql: 'project = IT AND text ~ "add-in crash" AND created > -90d' }, resultSummary: "1 strong match: IT-121544.", latencyMs: 640 }),
      tc({ id: "t3", tool: "jira.editJiraIssue", system: "Atlassian", intent: "Set component and duplicate link.", parameters: { issueKey: "IT-121611", components: "Outlook Add-in" }, verdict: "allowed", rule: "itsupport.write.metadata auto-approved for esq-agent-it-triage", latencyMs: 300 }),
    ],
  },
  {
    id: "run-4406",
    agentSlug: "transcript-production-reconciler",
    agentName: "Transcript Production Reconciler",
    title: "Delivery record sweep - 28 Aug",
    startedBy: "Schedule: weekdays 06:00 ET",
    trigger: "scheduled",
    startedAt: iso("2026-08-28T06:00:00-04:00"),
    state: "complete",
    correlationId: "cid-91ee3c07",
    costUsd: 0.61,
    tokens: 52_800,
    intentIds: ["AI-8830"],
    steps: [
      { id: "s1", label: "Intake", detail: "Scheduled trigger fired.", state: "done", at: "2026-08-28T06:00:00-04:00", durationMs: 60 },
      { id: "s2", label: "Plan", detail: "Sweep query built for produced-with-no-delivery.", state: "done", at: "2026-08-28T06:00:02-04:00", durationMs: 900 },
      { id: "s3", label: "Scan", detail: "4,110 worksheets scanned, 1 flagged as produced with no delivery.", state: "done", at: "2026-08-28T06:02:40-04:00", durationMs: 158_000 },
      { id: "s4", label: "Policy check", detail: "Low-risk enumerated field write; still requires OM approval by policy.", state: "done", at: "2026-08-28T06:02:43-04:00", durationMs: 120 },
      { id: "s5", label: "Await approval", detail: "Approved by Marisol Reyes at 08:14 ET.", state: "done", at: "2026-08-28T08:14:09-04:00", durationMs: 7_886_000 },
      { id: "s6", label: "Execute", detail: "Worksheet moved back to Processing. Idempotency key accepted once.", state: "done", at: "2026-08-28T08:14:11-04:00", durationMs: 640, attempts: 1 },
      { id: "s7", label: "Verify and receipt", detail: "Read-back confirmed 8 - Processing. Receipt RCPT-5590 written.", state: "done", at: "2026-08-28T08:14:13-04:00", durationMs: 420 },
    ],
    toolCalls: [
      tc({ id: "t1", tool: "netsuite.query_records", intent: "Find worksheets marked Produced with no delivery artifact.", parameters: { sql: "SELECT id FROM CUSTOMRECORD_WORKSHEET WHERE custrecord_ws_prod_status = 9 …" }, resultSummary: "1 worksheet on J14964046.", latencyMs: 2_400 }),
      tc({ id: "t2", tool: "netsuite.modify_record", intent: "Move the worksheet back to Processing.", parameters: { id: "881904", custrecord_ws_prod_status: "8" }, verdict: "approval-required", rule: "om.write.worksheet_status requires esq-ai-approvers-om", latencyMs: 120, actionIntentId: "AI-8830", resultSummary: "Approved and executed. Read-back confirmed." }),
    ],
  },
  {
    id: "run-4409",
    agentSlug: "expense-report-assembler",
    agentName: "Expense Report Assembler",
    title: "August receipts sweep",
    startedBy: "Jim Ballowe",
    trigger: "on-demand",
    startedAt: iso("2026-08-28T09:12:30-04:00"),
    state: "escalated",
    correlationId: "cid-5db27f44",
    costUsd: 0.22,
    tokens: 19_700,
    intentIds: [],
    steps: [
      { id: "s1", label: "Intake", detail: "Launched from the console.", state: "done", at: "2026-08-28T09:12:30-04:00", durationMs: 110 },
      { id: "s2", label: "Plan", detail: "Mailbox window set to 01-31 Aug.", state: "done", at: "2026-08-28T09:12:32-04:00", durationMs: 700 },
      { id: "s3", label: "Collect receipts", detail: "17 receipts found, 15 parsed cleanly.", state: "done", at: "2026-08-28T09:14:50-04:00", durationMs: 138_000 },
      { id: "s4", label: "File to Box", detail: "Upload retried twice on a 502 from the Box API, then succeeded for 15 of 15.", state: "done", at: "2026-08-28T09:16:22-04:00", durationMs: 92_000, attempts: 3, note: "Retry with exponential backoff, handled by the orchestrator." },
      { id: "s5", label: "Escalate", detail: "2 receipts could not be attributed to a cost center. Handed to a human queue.", state: "failed", at: "2026-08-28T09:16:40-04:00", note: "Agent stopped rather than guessing. No partial expense report was created." },
    ],
    toolCalls: [
      tc({ id: "t1", tool: "m365.outlook_email_search", system: "Microsoft 365", intent: "Find receipts in the August window.", parameters: { query: "receipt OR invoice OR order confirmation", window: "2026-08-01..2026-08-31" }, resultSummary: "17 messages.", latencyMs: 1_900 }),
      tc({ id: "t2", tool: "box.upload_file", system: "Box", intent: "File 15 normalized receipts.", parameters: { folderId: "204118773" }, resultSummary: "15 uploaded after 2 retries.", latencyMs: 92_000 }),
      tc({ id: "t3", tool: "netsuite.create_record", intent: "Create the expense report draft.", parameters: { recordType: "expensereport" }, verdict: "blocked", rule: "expense.write.report blocked while any line is unattributed", latencyMs: 90, resultSummary: "Blocked by policy. Run escalated to a human." }),
    ],
  },
  {
    id: "run-4411",
    agentSlug: "transcript-delivery-auditor",
    agentName: "Transcript Delivery Auditor",
    title: "Daily turnaround audit - 28 Aug",
    startedBy: "Schedule: daily 07:30 ET",
    trigger: "scheduled",
    startedAt: iso("2026-08-28T07:30:00-04:00"),
    state: "complete",
    correlationId: "cid-1ac93b56",
    costUsd: 0.88,
    tokens: 74_300,
    intentIds: [],
    steps: [
      { id: "s1", label: "Intake", detail: "Scheduled trigger fired.", state: "done", at: "2026-08-28T07:30:00-04:00", durationMs: 60 },
      { id: "s2", label: "Scan", detail: "612 transcripts produced in the trailing 7 days.", state: "done", at: "2026-08-28T07:32:40-04:00", durationMs: 160_000 },
      { id: "s3", label: "Report", detail: "9 late deliveries identified. Read-only agent, no writes attempted.", state: "done", at: "2026-08-28T07:33:30-04:00", durationMs: 4_100 },
    ],
    toolCalls: [
      tc({ id: "t1", tool: "netsuite.query_records", intent: "List transcripts produced in the last 7 days.", parameters: { sql: "SELECT … FROM CUSTOMRECORD_WORKSHEET WHERE …" }, resultSummary: "612 rows.", latencyMs: 8_200 }),
      tc({ id: "t2", tool: "box.search_files_metadata", system: "Box", intent: "Confirm delivery artifacts exist.", parameters: { template: "transcriptDelivery" }, resultSummary: "603 matched, 9 missing or late.", latencyMs: 6_400 }),
    ],
  },
];

export const LEDGER: LedgerEntry[] = [
  { id: "L-9912", at: "2026-08-28T13:59:06-04:00", kind: "attempt", runId: "run-4416", correlationId: "cid-c40b9911", actor: "agent:it-intake-triage", system: "Atlassian", summary: "jira.editJiraIssue on IT-121611 - attempt 1", payloadHash: "sha256:b81f…3c02" },
  { id: "L-9911", at: "2026-08-28T13:47:12-04:00", kind: "intent", runId: "run-4417", correlationId: "cid-2f81b4c0", actor: "agent:invoice-exception-handler", system: "NetSuite", summary: "ActionIntent AI-8841 raised - $2,340.00 credit memo", payloadHash: "sha256:9f2c…c31e", evidenceKey: "s3://esq-ai-evidence/2026/08/28/AI-8841/" },
  { id: "L-9910", at: "2026-08-28T13:31:40-04:00", kind: "intent", runId: "run-4415", correlationId: "cid-77a0e412", actor: "agent:deposition-scheduling-assistant", system: "NetSuite", summary: "ActionIntent AI-8839 raised - assign reporter to J15048812", payloadHash: "sha256:4b71…7d40", evidenceKey: "s3://esq-ai-evidence/2026/08/28/AI-8839/" },
  { id: "L-9908", at: "2026-08-28T12:58:03-04:00", kind: "intent", runId: "run-4412", correlationId: "cid-6b0d2ef8", actor: "agent:client-onboarding-packet", system: "Box", summary: "ActionIntent AI-8836 raised - 3 external collaborators on a confidential folder", payloadHash: "sha256:21d0…be82", evidenceKey: "s3://esq-ai-evidence/2026/08/28/AI-8836/" },
  { id: "L-9903", at: "2026-08-28T09:16:40-04:00", kind: "policy-block", runId: "run-4409", correlationId: "cid-5db27f44", actor: "gateway:mintmcp", system: "NetSuite", summary: "netsuite.create_record blocked - expense.write.report with 2 unattributed lines" },
  { id: "L-9902", at: "2026-08-28T09:16:41-04:00", kind: "escalation", runId: "run-4409", correlationId: "cid-5db27f44", actor: "orchestrator:stepfunctions", summary: "Run escalated to the AP human queue. No partial write occurred." },
  { id: "L-9898", at: "2026-08-28T08:14:13-04:00", kind: "receipt", runId: "run-4406", correlationId: "cid-91ee3c07", actor: "agent:transcript-production-reconciler", system: "NetSuite", summary: "RCPT-5590 - J14964046 worksheet read-back confirmed 8 - Processing", payloadHash: "sha256:7ac3…1a55", evidenceKey: "s3://esq-ai-evidence/2026/08/28/RCPT-5590/" },
  { id: "L-9897", at: "2026-08-28T08:14:11-04:00", kind: "attempt", runId: "run-4406", correlationId: "cid-91ee3c07", actor: "agent:transcript-production-reconciler", system: "NetSuite", summary: "netsuite.modify_record on worksheet 881904 - attempt 1, idempotency key accepted", payloadHash: "sha256:7ac3…1a55" },
  { id: "L-9896", at: "2026-08-28T08:14:09-04:00", kind: "approval", runId: "run-4406", correlationId: "cid-91ee3c07", actor: "user:Marisol Reyes", summary: "AI-8830 approved - payload unchanged, hash matched" },
  { id: "L-9890", at: "2026-08-28T07:33:30-04:00", kind: "receipt", runId: "run-4411", correlationId: "cid-1ac93b56", actor: "agent:transcript-delivery-auditor", summary: "Audit complete - 9 late deliveries reported, no writes attempted", evidenceKey: "s3://esq-ai-evidence/2026/08/28/run-4411/" },
  { id: "L-9884", at: "2026-08-28T06:02:44-04:00", kind: "intent", runId: "run-4406", correlationId: "cid-91ee3c07", actor: "agent:transcript-production-reconciler", system: "NetSuite", summary: "ActionIntent AI-8830 raised - worksheet production status correction", payloadHash: "sha256:7ac3…1a55" },
  { id: "L-9871", at: "2026-08-27T17:02:55-04:00", kind: "rejection", runId: "run-4402", correlationId: "cid-3e9a71d2", actor: "user:Nate Oduya", summary: "AI-8827 rejected - customer reply rewritten by hand" },
  { id: "L-9869", at: "2026-08-27T16:41:20-04:00", kind: "intent", runId: "run-4402", correlationId: "cid-3e9a71d2", actor: "agent:it-intake-triage", system: "Atlassian", summary: "ActionIntent AI-8827 raised - public customer reply on IT-121602", payloadHash: "sha256:e558…09cd" },
  { id: "L-9860", at: "2026-08-27T14:20:02-04:00", kind: "policy-block", runId: "run-4398", correlationId: "cid-88f01aa3", actor: "gateway:mintmcp", system: "Salesforce", summary: "salesforce.update blocked - agent workload has no write scope on Opportunity" },
];

/**
 * Scripted interactive sessions. Slide 3, "Interactive View": reads flow freely,
 * writes are gated tool-by-tool with inline confirmation for higher-risk actions.
 */
export const CHAT_SCRIPTS: Record<
  string,
  { prompt: string; reply: ChatMessage }[]
> = {
  "deposition-scheduling-assistant": [
    {
      prompt: "Which jobs next week still have no reporter assigned?",
      reply: {
        id: "m-1",
        author: "agent",
        at: "",
        text:
          "Seven jobs between 31 Aug and 4 Sep are still unstaffed. Four are routine and have three or more available certified reporters each. Three are tight:\n\nJ15048812, Ortega v. Meridian Freight, 3 Sep in Phoenix. Arizona CSR required and only one candidate is both certified and clear.\nJ15049320, Whitmore v. Cascade Utilities, 2 Sep in Bend, Oregon. Nearest available reporter is 78 miles out, so a travel fee applies.\nJ15051104, In re Sandoval, 4 Sep in Miami. Spanish interpreter needed and no interpreter is booked yet.\n\nI can staff the Phoenix job now if you want to start there.",
        toolCalls: [
          tc({ id: "c1", tool: "netsuite.query_records", intent: "List unstaffed jobs, 31 Aug to 4 Sep.", parameters: { sql: "SELECT id, entityid, jobdate FROM job WHERE …" }, resultSummary: "7 jobs.", latencyMs: 620 }),
          tc({ id: "c2", tool: "netsuite.lookup_job_details", intent: "Read requirements for each unstaffed job.", parameters: { jobIds: "7 ids" }, resultSummary: "3 jobs constrained.", latencyMs: 1_120 }),
        ],
      },
    },
    {
      prompt: "Staff the Phoenix job.",
      reply: {
        id: "m-2",
        author: "agent",
        at: "",
        text:
          "Grace Lindholm is the only candidate who clears every constraint. Active Arizona CSR through March 2027, calendar free 09:00 to 17:00 MST on 3 Sep, and 14 miles from the site so no travel fee.\n\nAssigning her changes the job in NetSuite, which I cannot do on my own. I have prepared exactly what would change. Confirm it below, or open the full detail first.",
        toolCalls: [
          tc({ id: "c3", tool: "netsuite.query_records", intent: "Screen AZ-certified reporters.", parameters: { state: "AZ" }, resultSummary: "9 candidates, 3 clear.", latencyMs: 540 }),
          tc({ id: "c4", tool: "m365.outlook_calendar_search", system: "Microsoft 365", intent: "Check 3 Sep availability.", parameters: { window: "2026-09-03T09:00/17:00" }, resultSummary: "Lindholm clear.", latencyMs: 880 }),
          tc({ id: "c5", tool: "netsuite.modify_record", intent: "Assign Grace Lindholm to J15048812 and set the job to Esquire Confirmed.", parameters: { id: "15048812", custentity_assigned_reporter: "EMP-2291", custentity_jobproductionstatus: "4" }, verdict: "approval-required", rule: "scheduling.write.assign_reporter requires esq-ai-approvers-scheduling", latencyMs: 150, actionIntentId: "AI-8839" }),
        ],
        pendingWrite: {
          toolCallId: "c5",
          confirmLabel: "Assign Grace Lindholm and confirm the job",
          intentId: "AI-8839",
        },
      },
    },
    {
      prompt: "Can you also email the firm to tell them it is covered?",
      reply: {
        id: "m-3",
        author: "agent",
        at: "",
        text:
          "I cannot. Sending email outside Esquire is not something I am allowed to do at all, so this was refused outright rather than sent to you to approve. It is not a judgement call you can override from here.\n\nIf emailing the firm should be part of this job, Priya Raman owns how this agent works and can request it. For now the confirmation wording is ready for you to send from Outlook yourself.",
        toolCalls: [
          tc({ id: "c6", tool: "m365.send_mail", system: "Microsoft 365", intent: "Email the ordering firm that coverage is confirmed.", parameters: { to: "external recipient" }, verdict: "blocked", rule: "gateway.scope: tool not granted to workload esq-agent-scheduling", latencyMs: 40, resultSummary: "Refused at the gateway. Nothing was sent." }),
        ],
      },
    },
  ],
  "transcript-production-reconciler": [
    {
      prompt: "Why did J14964046 come up in this morning's sweep?",
      reply: {
        id: "m-1",
        author: "agent",
        at: "",
        text:
          "Its transcript worksheet says Produced, but nothing was ever delivered behind it.\n\nTwo things should exist for a produced transcript and neither does: the transcriptionist submission timestamp is empty, and there is no delivery file in Box under this job. The transcription vendor has recorded no activity since 19 August either.\n\nSo I proposed moving the worksheet back to Processing, which puts it back in the production queue. Marisol approved that at 08:14 and I confirmed afterwards that the change took.",
        toolCalls: [
          tc({ id: "c1", tool: "netsuite.lookup_worksheet_details", intent: "Read the transcript worksheet on job 14964046.", parameters: { jobId: "14964046", type: "CR" }, resultSummary: "Status 9 - Produced, submission timestamp empty.", latencyMs: 280 }),
          tc({ id: "c2", tool: "box.search_files_metadata", system: "Box", intent: "Look for a delivery file under this job.", parameters: { template: "transcriptDelivery", job: "J14964046" }, resultSummary: "No match under any naming convention.", latencyMs: 640 }),
        ],
      },
    },
    {
      prompt: "How often does this happen?",
      reply: {
        id: "m-2",
        author: "agent",
        at: "",
        text:
          "Eleven times this month, and ten of the eleven trace to one bulk update on 24 August that moved a batch of worksheets to Produced without anything behind them.\n\nThat is a different shape of problem from the usual one. A steady trickle would point at a gap in the workflow. A single spike pointing at one bulk edit points at how that edit was made, which is worth a conversation with whoever ran it rather than a change to the system.\n\nThe eleventh is unrelated and was a genuine delivery that I could not find because it was filed under the old naming convention. Marisol caught that one and rejected my proposal, correctly.",
        toolCalls: [
          tc({ id: "c3", tool: "netsuite.query_records", intent: "Count produced-with-no-delivery cases this month.", parameters: { sql: "SELECT … FROM CUSTOMRECORD_WORKSHEET WHERE custrecord_ws_prod_status = 9 …" }, resultSummary: "11 cases, 10 sharing one edit timestamp.", latencyMs: 3_100 }),
        ],
      },
    },
    {
      prompt: "Can you fix the naming convention problem?",
      reply: {
        id: "m-3",
        author: "agent",
        at: "",
        text:
          "Not on my own. Searching both the old and new naming conventions is a change to my instructions, not something I can decide mid-run, and I would rather be wrong loudly than quietly widen my own search rules.\n\nMarisol Reyes owns how I work and can make that change. Until then I will keep flagging files under the old convention as missing, so treat a case with a populated submission timestamp as one to check by hand before approving.",
        toolCalls: [],
      },
    },
  ],
  "transcript-delivery-auditor": [
    {
      prompt: "Which deliveries were late this week?",
      reply: {
        id: "m-1",
        author: "agent",
        at: "",
        text:
          "Nine of 612 transcripts missed the committed turnaround, which is 1.5 percent against a 2 percent tolerance.\n\nSix of the nine trace to a single transcription vendor whose average turnaround slipped from 3.1 to 5.4 days this month. The other three are one-off: two client-requested holds and one worksheet that was never moved out of Processing.\n\nI am a read-only agent, so I have not changed anything. The vendor pattern is the one worth acting on.",
        toolCalls: [
          tc({ id: "c1", tool: "netsuite.query_records", intent: "List transcripts produced in the trailing 7 days.", parameters: { sql: "SELECT … FROM CUSTOMRECORD_WORKSHEET" }, resultSummary: "612 rows.", latencyMs: 8_200 }),
          tc({ id: "c2", tool: "box.search_files_metadata", system: "Box", intent: "Match delivery artifacts.", parameters: { template: "transcriptDelivery" }, resultSummary: "9 late or missing.", latencyMs: 6_400 }),
        ],
      },
    },
  ],
};

export const DEFAULT_CHAT: { prompt: string; reply: ChatMessage }[] = [
  {
    prompt: "What can you do?",
    reply: {
      id: "m-d1",
      author: "agent",
      at: "",
      text:
        "This agent does not have a scripted demo conversation yet. In the real system this is a live session, and each step it takes appears here as it happens.\n\nYou would see the same three outcomes as everywhere else: it looks something up and tells you, it makes a small routine change and records it, or it stops and asks you to approve something before it happens.",
      toolCalls: [],
    },
  },
];
